artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: data/student-scores.xlsx
  local_data_file: artifacts/data_ingestion/data.xlsx
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  preprocessor_obj_file_path: artifacts/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl
  all_params: params.yaml
  metric_file_name: artifacts/model_evaluation/metrics.json

mlflow_config:
  mlflow_uri: https://dagshub.com/username/student_performance_ml_project.mlflow
  mlflow_tracking_username: username
  mlflow_tracking_password: your_dagshub_token
